# Generated by Django 4.2.5 on 2023-11-22 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0004_task_datetime_created_task_datetime_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='Management.task', verbose_name='commands'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to=settings.AUTH_USER_MODEL, verbose_name='commands'),
        ),
    ]
