# Generated by Django 4.2.5 on 2023-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, upload_to='task_cover/', verbose_name='task_image'),
        ),
    ]
